"""add phone number

Revision ID: 10368d83b75c
Revises: 4849da8f700c
Create Date: 2022-05-01 01:16:25.656878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10368d83b75c'
down_revision = '4849da8f700c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
